### submit
POST {{base_url}}/submit

{"url": "https://www.jenn.site/after-my-dad-died-we-found-the-love-letters/"}

### submit
POST {{base_url}}/submit

{"url": "https://jenn.site/dissolution/"}


### RSS
GET {{base_url}}/feed/rss


### ATOM
GET {{base_url}}/feed/atom


### EPUB
GET {{base_url}}/feed/epub


### List
GET {{base_url}}/


### Refresh
POST {{base_url}}/refresh-feeds/

### clear
DELETE {{base_url}}/
